### ISSUE TITLE
Make link to GitHub repo in tutorial more explicit?

### ISSUE THREAD

**Issue by NickleDave** [ctb/2019-snakemake-ucdavis#1]
Hi @ctb, thanks for putting together this great tutorial.
Do you think it would be worth putting a link to this repo in the tutorial?
Sorry if it's there and I'm not seeing it.
I wanted to set this up locally instead of run on MyBinder but had to google to find it.
Just a suggestion, thanks!

**Comment by NickleDave** [comment]
Oh nvm just realized I should've clicked on " full set of installed software requirements [here]". I changed the issue name 😳
And by "more explicit" I don't mean "use curse words" but just have a link that says "you can get a copy of all the code we'll use here".

**Comment by ctb** [comment]
effin' A!

;)

see d22edec - works?

**Comment by NickleDave** [comment]
LfGTM! :D
Thanks
